FROM python:3.8-slim-buster as base

FROM base as builder

RUN mkdir /install
WORKDIR /install
COPY requirements.txt /requirements.txt
RUN apt-get update && \
    apt-get install -y netcat-openbsd gcc && \
    apt-get clean && \
    pip install --prefix=/install -r /requirements.txt --no-warn-script-location

FROM base

EXPOSE 5000
COPY --from=builder /install /usr/local
COPY . /TakeOnDBLoad
WORKDIR /TakeOnDBLoad

# run the application
CMD ["python", "/TakeOnDBLoad/flask_app.py"]