---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.15"

resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/gowhale/MyFirstLocalPipeline.git
      branch: dev

  - name: docker-config-flask
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/flask


jobs:
  - name: gowhale-hello-world
    public: true
    serial: true
    plan:
      - get: resource-tutorial
        trigger: true
      - task: hello-world
        file: resource-tutorial/hello_world.yml

  - name: "Docker-Build-Flask"
    public: false
    plan:
      - get: resource-tutorial
        trigger: true
      - put: docker-config-flask
        params:
          # The path of a directory containing a Dockerfile to build
          build: resource-tutorial
          tag_as_latest: true


