---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/gowhale/MyFirstLocalPipelinet
      branch: master

  - name: my-timer
    type: time
    source:
      interval: 2m

jobs:
  - name: job-hello-world
    public: true
    serial: true
    plan:
      - get: resource-tutorial
      - get: my-timer
        trigger: true
      - task: hello-world
        file: resource-tutorial/hello_world.yml